blank_lines_upper_bound = 2
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hex_literal_case = "Lower"
imports_granularity = "Module"
inline_attribute_width = 60
match_block_trailing_comma = true
newline_style = "Unix"
normalize_comments = true
overflow_delimited_expr = true
struct_lit_width = 40
use_field_init_shorthand = true
wrap_comments = true
