[package]
name = "mwm"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bevy_app = "0.6"
bevy_ecs = "0.6"
log = "0.4"
mwm_xcb = { path = "../mwm_xcb" }
pretty_env_logger = "0.4"
rustc-hash = "1.1"
