[package]
name = "mwm_xcb"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bevy_app = "0.7"
bevy_ecs = "0.7"
log = "0.4"
rustc-hash = "1.1"
xcb = { version = "1.1", features = ["randr"] }
